#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Adyen\Core\Console\Commands\GenerateCurrencyAmountMapCommand;
use Symfony\Component\Console\Application;

$app = new Application();

// Add all custom Core commands here.
$app->add(new GenerateCurrencyAmountMapCommand());

$app->run();
